### ISSUE TITLE
Document how to use require and external options

### ISSUE THREAD

**Issue by stubailo** [elidoran/cosmos-browserify#10]
There are options for the command line tool, but in the API they are methods to call (why is it different? who knows?)

browserify.require: https://github.com/substack/node-browserify#brequirefile-opts

browserify.external: https://github.com/substack/node-browserify#bexternalfile

Probably can be implemented in much the same way as transforms; I know the Grunt plugin has them as JSON options so we can copy that. https://github.com/jmreidy/grunt-browserify#require

**Comment by stubailo** [comment]
Never mind, the require option actually works already, it's just not documented lol. Going to document it in a sec

**Comment by stubailo** [comment]
OK I think the external option might be the same ... hooray for undocumented options...

**Comment by pors** [comment]
It seems that `ReactRouter = require("react-router");` only works when `cosmos:browserify` is explicitely added to the meteor project. It is also part of the `react` package, but that doesn't do it for me, I get `Uncaught ReferenceError: require is not defined` in that case.

Any idea how this can be solved?

**Comment by pors** [comment]
The example app has it added explicitely as well: https://github.com/meteor/react-packages/blob/master/examples/react-todos/.meteor/packages

**Comment by elidoran** [comment]
You only need cosmos:browserify in your app when you have app files to browserify. 

Packages must call `api.use('cosmos:browserify', 'client')` when they have files they need to browserify.

Each package needing it must call `api.use('cosmos:browserify', 'client')` for itself; as with all packages.

The _react-todos_ you referenced is an app and has cosmos:browserify in the app scope because it has [app files to browserify](https://github.com/meteor/react-packages/tree/master/examples/react-todos/client/lib).

Also, the options file there shows an outdated way to externalify react. Look way down near the bottom of [this page](http://react-in-meteor.readthedocs.org/en/latest/client-npm/) to see this:

``` javascript
{
  "transforms": {
    "externalify": {
      "global": true,
      "external": {
        "react": "Package.react-runtime.React.require"
      }
    }
  }
}
```

**Comment by pors** [comment]
Ah OK, so to use browserify in an app (as opposed to in a package) it is needed to add cosmos:browserify even though it is part of the react package. 
That makes things clear, thanks @elidoran !

**Comment by elidoran** [comment]
Yes, it's the way all packages work. They are scoped to only be available to packages depending on them and an app when added. 

Also, there are instructions for using it in an app in the README [here](https://github.com/elidoran/cosmos-browserify#use-in-a-meteor-app). Step 3 says to add cosmos:browserify to your app. :)

**Comment by elidoran** [comment]
Added some code plus documentation for: ignore, exclude, external, and plugin. That doesn't contain 'require' tho. Almost.

**Comment by elidoran** [comment]
Newer Meteor doesn't require this plugin (thank you MDG).
