### ISSUE TITLE
Which approach for Meteor?  

### ISSUE THREAD

**Issue by bartonhammond** [elidoran/cosmos-browserify#18]
First you say look at [cosmos-browserify-example](http://github.com/elidoran/cosmos-browserify-example) which the .meteor.packages :

```
meteor-platform
cosmos:browserify-example
coffeescript
cosmos:browserify-example2
cosmos:browserify
```

do **not** contain meteorhacks:npm.

Then later in the Meteor [Use in a Meteor App](https://github.com/elidoran/cosmos-browserify#use-in-a-meteor-app) you say 

```
$ meteor add meteorhacks:npm
```

I'm confused.

I am developing a FOO package that has a "package" directory that brings in "XX".  I have a separate project BAR that uses my FOO package.  I followed the cosmos:browserify-example and my project BAR does not see the "XX" that was exported from FOO.

**Comment by elidoran** [comment]
I updated the example app to have the missing app level cosmos:browserify use.

If you are making a **package FOO** which uses cosmos:browserify then you don't need to add cosmos:browserify to your **app BAR**; unless you are also browserify'ing an app file.

If you want your **app BAR** to have access to a variable from **any** package, you must export it from that package. So, your **package FOO** must have the following line in its _package.js_: `api.export('appUppercase', 'client');` See this example in the first example package's [package.js](https://github.com/elidoran/cosmos-browserify-example/blob/master/packages/browserify-example/package.js#L30). See how the exported variable name matches a variable created in the [browserify file](https://github.com/elidoran/cosmos-browserify-example/blob/master/packages/browserify-example/client.browserify.js#L7).

**Comment by bartonhammond** [comment]
Still no luck. 

My app "boilerplate/webix" has a symnlink to my package "webix" for local package development and that works fine. I've been developing for some time w/ no problems.  

I'm am trying to bring in the  "keysim" NPM module.

My package "webix" now has the following directory structure after adding the "packages/keysim"

```
 drwxr-xr-x  12 barton  staff   408 Sep 18 08:27 ..
  drwxr-xr-x  14 barton  staff   476 Sep 21 08:13 .git
  drwxr-xr-x  10 barton  staff   340 Sep 21 08:16 .meteor
  drwxr-xr-x   2 barton  staff    68 Sep 20 18:32 .npm
  -rw-r--r--   1 barton  staff  9177 Sep 19 18:48 README.md
  drwxr-xr-x  16 barton  staff   544 Sep 20 19:19 lib
  -rw-r--r--   1 barton  staff  2181 Sep 21 08:15 package.js
  drwxr-xr-x   3 barton  staff   102 Sep 20 18:34 packages
```

My "packages/keysim" has three files:
packages/keysim/client.browserify.js:

```
// w/out var it becomes a package scoped variable
keysim1 = require('keysim');
// we'll make this one global scoped via api.export() in package.js
Keysim = keysim1;
```

packages/keysim/client.browserify.options.json is:

```
{
  "transforms": {
    "envify": {
      "NODE_ENV": "production",
      "_": "purge"
    }
  }
}
```

and my packages/keysim/package.js is:

```
Package.describe({
  name: 'useraccounts:webix-keysim',
  version: '0.0.1',
  summary: 'Sim keyboard'
});

// Declare NPM modules for Meteor to download into .npm/package
Npm.depends({
  'keysim':'1.3.0'
});


Package.onUse(function(api) {
  api.versionsFrom(['METEOR@1.0']);

  api.use(['cosmos:browserify@0.5.1'], 'client'); // need this package

  api.addFiles([
      'client.browserify.js',           // browserify file
      'client.browserify.options.json'  // browserify options file
    ],
    'client'
              );

  // export it to global app scope
  api.export('Keysim','client');

});
```

My ./.meteor/packages has:

```
meteor-platform
autopublish
insecure
useraccounts:webix-keysim
```

and my package.js first three lines has this:

```
Package.onUse(function(api) {

  api.versionsFrom(['METEOR@1.0']);

  api.export('Keysim','client');
```

That's all for the package "webix"

And finally, my app "boilerplate/webix" has the following ./.meteor/packages:

```

meteor-platform
accounts-password
accounts-google
service-configuration
useraccounts:iron-routing
useraccounts:webix
meteorhacks:npm
npm-container
```

And the "boilerplate/webix/packages.json:

```
{
  "keysim" : "1.3.0"
}
```

When I am in the "boilerplate/webix" app, and stop in the debugger,  Keysim is "undefined" 

I'm still confused as to what to do.  I appreciate your help.

**Comment by bartonhammond** [comment]
Ok, I finally figured it out. 
I made a separate package for my npm module "keysim".  So I have three "projects", my "boilerplate/webix" application, my "webix" and now my "webix-keysim".

My webix-keysim looks similar to [cosmos browserify example](http://github.com/elidoran/cosmos-browserify-example).  It exports "Keysim".

My "webix" package knows nothing about "webix-keysim"

My "boilerplate/webix" application has the following in ./.meteor/packages:

```
meteor-platform
accounts-password
accounts-google
service-configuration
useraccounts:iron-routing
useraccounts:webix
meteorhacks:npm
npm-container
cosmos:browserify
useraccounts:webix-keysim
```

And it's packages.json is:

```
{
  "keysim" : "1.3.0"
}
```

I got confused there for a bit.  Once I realized the NPM stuff had to be a separate package and not just additional stuff inside my "webix" package, it worked out well.

Thanks for your help!

**Comment by elidoran** [comment]
To get the **keysim** module from NPM you only need to require it once. It looks like you are requiring it in both the package and the app. Instead, require it in the _package.js_ file of your **package** using `Npm.depends()`, export it, and then add the package to your **app**.

A **package** doesn't have a .meteor/packages file. That's for an app. A **package** doesn't have directories: _.meteor_ and _packages_. That's also for an **app**. The "webix" is supposed to be a package, but, it looks like an app directory. To use another package in a package, you need only specify it in your _package.js_ file like the call to use _cosmos:browserify@0.5.1_ in your description. You don't need to set it up like an app and use `meteor add`. Create the package via `meteor create --package useraccounts:webix`.

When you use `Npm.depends()` to get _keysim_ into your package, then, you don't need to also get it in your app via the _packages.json_ file.

Here's a sample layout:

```
stuff/
  webixKeysimPackage/
    client.browserify.js - use the two vars as you showed above 
    client.browserify.options.json - above you have the defaults, so you don't need this file
    package.js - use Npm.depends() and api.export() like you showed above
  webixPackage/
    package.js
  webixApp/
    packages/
      webixKeysimPackage/ - symlink to ../../webixKeysimPackage
      webixPackage/ - symlink to ../../webixPackage
```

When you have this structure, add each package to your app via `meteor add useraccounts:<name>`. 

Run the app and `Keysim` will be globally available, because of the `api.export()` call in webixKeysimPackage.

You don't need the _packages.json_ file in your app, unless you want an NPM module other than _keysim_. 

You don't need to add the _cosmos:browserify_ package to your app directly, unless you are going to browserify something else, which is an app file.

Make _webix-keysim_ look like this package: [browserify-example](https://github.com/elidoran/cosmos-browserify-example/tree/master/packages/browserify-example).

_edit:_ Removed reference to make your app like like the example app. It is browserifying a file and you're not doing that at the app level. So, that statement was confusing. _:edit_

After rereading your posts it seems you may have followed both sets of instructions. The README has one set of instructions for making a package which browserifies a file, and a second set of instructions for how an app browserifies a file. You don't need to follow both. It seems your intent is making a package which browserifies _keysim_. So, only follow the instructions  [Use in a Meteor Package](https://github.com/elidoran/cosmos-browserify#use-in-a-meteor-package) (I also removed the confusing `meteor add` command from those instructions).

**Comment by bartonhammond** [comment]
Ok - thanks for the clarification. I'll clean up my tangleness...thanks

**Comment by elidoran** [comment]
Thank you for pointing out multiple places where my documentation and examples need improvement.
