### ISSUE TITLE
documentation improvement

### ISSUE THREAD

**Issue by elidoran** [elidoran/cosmos-browserify#2]
Please, provide feedback on my README and I will revise it.

**Comment by elidoran** [comment]
@mikowals  Is the README understandable? Any suggestions for revising it?

**Comment by mikowals** [comment]
Some suggestions for the 'Easy as 1 2 3' section.

Both `browserify.js` and the file demonstrating `uppercase` working need to be included with `api.addFiles()`:

```
Package.onUse(function(api) {
  api.use(['cosmos:browserify'], 'client');
  api.addFiles(['browserify.js','example.js'],'client');
}); 
```

On a more stylistic note, it might be better to show `uppercase` being exported (`api.export('uppercase',client')`) so that it can just be tested in the browser dev console manually.  Exporting variables for use outside of the package will be common, particularly for beginners, so maybe showing that avoids future questions. 

Completing the example repo with the code referenced in the README would make everything abundantly clear.

**Comment by elidoran** [comment]
@mikowals  Great suggestions, thank you. I updated the README with your suggestions. I still need to update the 'Install and Usage' section to focus more on having the `api.export()` and testing it in the console. I published the example app, finally.

**Comment by elidoran** [comment]
I rewrote the README with a table of contents and focusing on whether the user wants to use it in a package or an app.
