### ISSUE TITLE
resolving locally installed packages

### ISSUE THREAD

**Issue by sclausen** [elidoran/cosmos-browserify#25]
It would be nice to require a file relative to the package path which uses `cosmos:borwserify` like `require('node_modules/lodash/math.js')`.
It seems, that it's required to use `Npm.depends`, because now I get an error like

```
Cannot find module
   'node_modules/lodash/math.js' from
   '/tmp/test/packages/math/.npm/package'
```

**Comment by elidoran** [comment]
You mean you are using `require()` in the file you are browserifying to get a module in a _node_modules_ directory you created manually?

_cosmos:browserify_ is a wrapper around the [browserify](http://browserify.org) tool which uses the npm modules installed by Meteor's `Npm.depends()` calls. It explicitly sets the `basedir` for the browserify tool to the directory where Meteor installs the npm modules. Which is in _.npm/package_ for a local package and _../npm_ for a published package added to an app (it's actually way more complicated to find that directory, see [this issue](https://github.com/elidoran/cosmos-browserify/issues/22#issuecomment-144640971)).

You can _override_ the _basedir_ value by using an options file:
1. create an options file next to the file you're browserifying with the extension changed from _.browserify.js_ to _.browserify.options.json_
2. specify a _basedir_ property with a path to the directory containing the _node_modules_ directory.  

Although this will work in a local package I believe it will not work if you intend to _publish_ the package to add to other apps via `meteor add ...`. As of Meteor 1.2 it no longer builds a package when it publishes it. So, `meteor add ...` installs it into a user's _~/.meteor/packages_ directory with a **different directory structure** and is built from there. Also, paths are resolved from the root of the app, or, from where the `meteor test-packages` command is run... so, if you specify a basedir value it will be resolved differently depending on what you're doing and where the package is being used.

It is possible for me to provide additional functionality based on options you specify in the options file which would perform this work based on locally installed node modules so it would work in all variations. Is there a reason to install the modules manually instead of using `Npm.depends()` ?

**Comment by sclausen** [comment]
Many thanks for your detailed explanation! There is indeed a very reasoned usecase: meteor's npm version is 1.4.6 and thus not capable of using scoped-packages, which prevents using `angular@2.0.0-alpha.38` because since this version it has `@reactivex/rxjs` as a dependency.

**Comment by elidoran** [comment]
That's interesting, both Meteor being so far behind on their NPM version and the new scopes for npm (which I hadn't known about, thank you).

Hopefully Meteor will move their node/npm versions up now that iojs/nodejs have combined forces and released node 4 and npm 3.

I'm keeping this need in mind for my next revision. It would be possible to allow using npm yourself and then have this plugin find the node_modules directory. I'll have to test to see if that directory ends up in the published package in an expected location. Finding these locations is a bit of a nightmare because of all the different places packages end up (with different formats) and different ways of running them.

**Comment by billyvg** [comment]
Another reason to install modules manually is if you're actively working on an npm package that is not published yet (or is not up to date).  Ideally you could just `npm link` the package while you're developing.

**Comment by elidoran** [comment]
At present, it works for an app and for a **local package** by specifying the `basedir` in the option file.

When I get time I'll make this work for **published packages**.

For example, in your app's _client_ directory:
1. create an app and cd into it
2. create a _client_ directory and cd into it
3. type: `npm install upper-case` to install the npm module there into _node_modules_ directory
4. create file _app.browserify.js_ with `uppercase = require('upper-case')` (normally put it into the _lib_ directory...)
5. create file _app.browserify.options.json_ with `{ "basedir" : "client" }` (it's relative to the root of the app)
6. run your app and in dev console you'll see _uppercase_ is available for use

As for packages, you can make it work already using the same thing, but, only for **local packages**.

A working example:
1. create a package named _bd_, in _app/packages_, or, not in an app, and `cd` into it
2. type: `npm install upper-case` to install the npm module there into _node_modules_ directory
3. create file _package.browserify.js_ with `uppercase = require('upper-case')`
4. in _package.js_ add the file and provide the basedir option all in one with an undocumented feature: `api.addFiles('package.browserify.js', 'client', { basedir: 'bd'});`
5. to test it works, add this to the test file:
   
   ``` javascript
   Tinytest.add('uppercase', function (test) {
     test.isNotNull(uppercase, 'uppercase should be available');
     test.equal(uppercase('testing'), 'TESTING', 'should capitalize "testing"');
     console.log('TESTING = ',uppercase('testing'));
   });
   ```
6. use `meteor test-packages ./` while in the package's directory, or,
7. use `meteor test-packages bd/` while in its parent directory (this is why I said use `basedir:'bd'` instead of `basedir:'.'`, when I tested it it worked with a basedir of _bd_ while in the package and in its parent)
8. to use _meteor test-packages_ from both the root of an app and inside the package's directory change the basedir to _packages/bd_.
9. This will also work: _packages/username_bd_ (when you create a normal package with a username prefix)

For a **published package** things become a lot more complicated because the Build API does not provide easy access to directories in _~/.meteor/packages_ to point Browserify at the correct directory containing _node_modules_.

In an attempt to see what I have to work with I figured out these things:
1. when creating a package in _app/packages_, use the username followed by an underscore in front of the package name. _meteor create username:packagename_ doesn't prefix it with the username, but, it will work when you put the username in there. This also still works for _meteor test-packages ./_ and _meteor test-packages packages/username_packagename_.
2. A published package won't publish the _node_modules_ directory, unless, you add them as assets via: `api.addAssets('node_modules/upper-case/upper-case.js', 'client')`. It doesn't accept directories, so, you must specify each file from the node module which you want to include in the published package (yes, I realize this could be **a lot** of files).
3. The files, _assets_, are published to: _~/.meteor/packages/username_packagename/0.0.1/web.browser/packages_ (the 0.0.1 represents the version of the package, I just used 0.0.1 as an example).
4. I need to get the _web-browser_ directory (or _web.cordova_... sometimes?) to then use the basedir value specified in the options (the one which works for _meteor test-packages_ command).

I'm finding a nearby directory for the npm stuff already, so, it's a matter of knowing to search for the other directory and append the specified basedir.

So, it **is** possible to make this work for a published package. It will require a bit of code changes.

(To Build API authors, please make an API to get the root directory of published packages and its npm directory.)

**Comment by elidoran** [comment]
Also, I was reminded by [my code](https://github.com/elidoran/cosmos-browserify/blob/master/plugin/browserify.coffee#L57) it uses the app root as the basedir of an app by default. So, using npm install at the app root will make it work without making an options file to set the basedir. The instructions above are appropriate when installing the npm modules into the client directory (or any directory other than the app root).

**Comment by elidoran** [comment]
Okay, version 0.9.0 does a bit of work [here](https://github.com/elidoran/cosmos-browserify/blob/master/plugin/browserify.coffee#L45) and [here](https://github.com/elidoran/cosmos-browserify/blob/master/plugin/browserify.coffee#L250) to use a _basedir_ option even for **published packages**.

I've tested it myself in multiple ways, but, after going round and round on it, I'd appreciate some feedback from you guys: @sclausen @billyvg  Then, I need to update the README to contain explanations of the _basedir_ option, as I did above in this issue.

I tested on a package using basedir `packages/username_package-name`:
1. in the package with: `meteor test-packages ./`
2. in parent directory: `meteor test-packages username_package-name`
3. in app root: `meteor test-packages packages/username_package-name`
4. in a published package added to an app

**Comment by elidoran** [comment]
Cleaned this up with 0.9.1.

**Comment by sclausen** [comment]
@elidoran currently I'm very busy with paid work, but I'll total catch up on this soon. Great work you did here!

**Comment by elidoran** [comment]
Closing for now, feel free to comment or even reopen.
