### ISSUE TITLE
missing npm modules

### ISSUE THREAD

**Issue by aon108** [elidoran/cosmos-browserify#37]
I've added this npm package https://www.npmjs.com/package/lda using the instructions. 

whenever i try and run on the client i get the following error:
"Cannot find module './stopwords_en.js' "

which i can see in root/packages/npm-container/.npm/package/node_modules/lda/lib

in the main npm package the line that's throwing the error is:
var stopwordsLang = require('./stopwords_en.js');

Which I imagine is not being found.

The package works fine when using on server.

To i need to install the npm package in a different way to use on client? Thanks

**Comment by elidoran** [comment]
You're right, that require statement isn't being found. The line is:

``` javascript
var stopwordsLang = require('./stopwords_' + value + ".js");
```

How would Browserify know which files to grab, at processing time, and include in the resulting file? It would have to first find that variable require. Then, look for all possible results of it as files. I think Browserify doesn't even find variable requires like that. 

If it was implemented like: 

``` javascript
var stopwordsLang;
if (value === 'en') stopwordsLang = require('./stopwords_en.js');
else if (value === 'de') stopwordsLang = require('./stopwords_de.js');
```

Then I think Browserify would find those two require statements and include their contents.

It's found on the server because it can actually look for that file on the file system and find it. In the browser, via Browserify, Browserify has to find everything when processing the files and include them in the browserified file for it to be available.

**Comment by aon108** [comment]
Thank you for such a swift reply. I can see how that value would be causing issues.

Could you recommend the best to install the package, so I can make the adjustments and use it on client? Thank you.

**Comment by elidoran** [comment]
You could make require calls for each of the language files in your file so Browserify will include them in its result. Then, they'll be available when the library does a require to get them.

**Comment by elidoran** [comment]
Feel free to reopen or add comments.
